### ISSUE TITLE
Maybe a Simple Usage Problem?

### ISSUE THREAD

**Issue by drbobbeaty** [cloverage/cloverage#83] opened 2015-08-14 20:59 UTC
I've recently added Cloverage to four of my projects. The first, a library that's used in the other three, tests fine and given me good results - to the limits of the tool, which is _fine_. Most importantly _**it runs**_.

Then when I run Cloverage on any of the projects that has that built library as a `:dependency`, I get the following:

``` bash
whimpy{bobbeaty}531: lein cloverage
Exception in thread "main" java.lang.ExceptionInInitializerError, compiling:(cloverage/report.clj:1:1)
    at clojure.lang.Compiler.load(Compiler.java:7142)
    at clojure.lang.RT.loadResourceScript(RT.java:370)
    at clojure.lang.RT.loadResourceScript(RT.java:361)
    at clojure.lang.RT.load(RT.java:440)
    at clojure.lang.RT.load(RT.java:411)
    at clojure.core$load$fn__5066.invoke(core.clj:5641)
    at clojure.core$load.doInvoke(core.clj:5640)
    at clojure.lang.RestFn.invoke(RestFn.java:408)
    at clojure.core$load_one.invoke(core.clj:5446)
    at clojure.core$load_lib$fn__5015.invoke(core.clj:5486)
    at clojure.core$load_lib.doInvoke(core.clj:5485)
    at clojure.lang.RestFn.applyTo(RestFn.java:142)
    at clojure.core$apply.invoke(core.clj:626)
    at clojure.core$load_libs.doInvoke(core.clj:5528)
    at clojure.lang.RestFn.applyTo(RestFn.java:137)
    at clojure.core$apply.invoke(core.clj:628)
    at clojure.core$use.doInvoke(core.clj:5618)
    at clojure.lang.RestFn.invoke(RestFn.java:436)
    at cloverage.coverage$eval914$loading__4958__auto____915.invoke(coverage.clj:1)
    at cloverage.coverage$eval914.invoke(coverage.clj:1)
    at clojure.lang.Compiler.eval(Compiler.java:6703)
    at clojure.lang.Compiler.eval(Compiler.java:6692)
    at clojure.lang.Compiler.load(Compiler.java:7130)
    at clojure.lang.RT.loadResourceScript(RT.java:370)
    at clojure.lang.RT.loadResourceScript(RT.java:361)
    at clojure.lang.RT.load(RT.java:440)
    at clojure.lang.RT.load(RT.java:411)
    at clojure.core$load$fn__5066.invoke(core.clj:5641)
    at clojure.core$load.doInvoke(core.clj:5640)
    at clojure.lang.RestFn.invoke(RestFn.java:408)
    at clojure.core$load_one.invoke(core.clj:5446)
    at clojure.core$load_lib$fn__5015.invoke(core.clj:5486)
    at clojure.core$load_lib.doInvoke(core.clj:5485)
    at clojure.lang.RestFn.applyTo(RestFn.java:142)
    at clojure.core$apply.invoke(core.clj:626)
    at clojure.core$load_libs.doInvoke(core.clj:5524)
    at clojure.lang.RestFn.applyTo(RestFn.java:137)
    at clojure.core$apply.invoke(core.clj:626)
    at clojure.core$require.doInvoke(core.clj:5607)
    at clojure.lang.RestFn.invoke(RestFn.java:408)
    at user$eval899$fn__901.invoke(form-init4106821147930786984.clj:1)
    at user$eval899.invoke(form-init4106821147930786984.clj:1)
    at clojure.lang.Compiler.eval(Compiler.java:6703)
    at clojure.lang.Compiler.eval(Compiler.java:6693)
    at clojure.lang.Compiler.load(Compiler.java:7130)
    at clojure.lang.Compiler.loadFile(Compiler.java:7086)
    at clojure.main$load_script.invoke(main.clj:274)
    at clojure.main$init_opt.invoke(main.clj:279)
    at clojure.main$initialize.invoke(main.clj:307)
    at clojure.main$null_opt.invoke(main.clj:342)
    at clojure.main$main.doInvoke(main.clj:420)
    at clojure.lang.RestFn.invoke(RestFn.java:421)
    at clojure.lang.Var.invoke(Var.java:383)
    at clojure.lang.AFn.applyToHelper(AFn.java:156)
    at clojure.lang.Var.applyTo(Var.java:700)
    at clojure.main.main(main.java:37)
Caused by: java.lang.ExceptionInInitializerError
    at java.lang.Class.forName0(Native Method)
    at java.lang.Class.forName(Class.java:348)
    at clojure.lang.RT.loadClassForName(RT.java:2093)
    at clojure.lang.RT.load(RT.java:430)
    at clojure.lang.RT.load(RT.java:411)
    at clojure.core$load$fn__5066.invoke(core.clj:5641)
    at clojure.core$load.doInvoke(core.clj:5640)
    at clojure.lang.RestFn.invoke(RestFn.java:408)
    at clojure.core$load_one.invoke(core.clj:5446)
    at clojure.core$load_lib$fn__5015.invoke(core.clj:5486)
    at clojure.core$load_lib.doInvoke(core.clj:5485)
    at clojure.lang.RestFn.applyTo(RestFn.java:142)
    at clojure.core$apply.invoke(core.clj:626)
    at clojure.core$load_libs.doInvoke(core.clj:5524)
    at clojure.lang.RestFn.applyTo(RestFn.java:137)
    at clojure.core$apply.invoke(core.clj:626)
    at clojure.core$require.doInvoke(core.clj:5607)
    at clojure.lang.RestFn.invoke(RestFn.java:457)
    at cheshire.core$loading__4958__auto__.invoke(core.clj:1)
    at cheshire.core__init.load(Unknown Source)
    at cheshire.core__init.<clinit>(Unknown Source)
    at java.lang.Class.forName0(Native Method)
    at java.lang.Class.forName(Class.java:348)
    at clojure.lang.RT.loadClassForName(RT.java:2093)
    at clojure.lang.RT.load(RT.java:430)
    at clojure.lang.RT.load(RT.java:411)
    at clojure.core$load$fn__5066.invoke(core.clj:5641)
    at clojure.core$load.doInvoke(core.clj:5640)
    at clojure.lang.RestFn.invoke(RestFn.java:408)
    at clojure.core$load_one.invoke(core.clj:5446)
    at clojure.core$load_lib$fn__5015.invoke(core.clj:5486)
    at clojure.core$load_lib.doInvoke(core.clj:5485)
    at clojure.lang.RestFn.applyTo(RestFn.java:142)
    at clojure.core$apply.invoke(core.clj:626)
    at clojure.core$load_libs.doInvoke(core.clj:5524)
    at clojure.lang.RestFn.applyTo(RestFn.java:137)
    at clojure.core$apply.invoke(core.clj:626)
    at clojure.core$require.doInvoke(core.clj:5607)
    at clojure.lang.RestFn.invoke(RestFn.java:457)
    at cloverage.report$eval1190$loading__4958__auto____1191.invoke(report.clj:1)
    at cloverage.report$eval1190.invoke(report.clj:1)
    at clojure.lang.Compiler.eval(Compiler.java:6703)
    at clojure.lang.Compiler.eval(Compiler.java:6692)
    at clojure.lang.Compiler.load(Compiler.java:7130)
    ... 55 more
Caused by: java.lang.ClassNotFoundException: com.fasterxml.jackson.dataformat.cbor.CBORFactory
    at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    at java.lang.Class.forName0(Native Method)
    at java.lang.Class.forName(Class.java:264)
    at cheshire.factory__init.__init0(Unknown Source)
    at cheshire.factory__init.<clinit>(Unknown Source)
    ... 99 more
whimpy{bobbeaty}532:
```

I installed it in the `project.clj` just exactly like the project where it _works_, but in all three other projects, it gives me this error.

Any ideas?

**Comment by ivajloip** [comment] 2015-11-19 14:42
I have the same problem. Has anybody managed to resolve it?

**Comment by MichaelBlume** [comment] 2015-11-22 01:36
Just got this today, will update if I sort it

**Comment by codeitagile** [comment] 2016-02-10 09:53
I am getting this today

**Comment by lumengxi** [comment] 2016-03-27 00:02
Any working solutions so far? Got same errors.

**Comment by rm-hull** [comment] 2016-08-09 23:44
> @drbobbeaty: I've recently added Cloverage to four of my projects.

Can you post your any of your _project.clj_'s, or more specifically the bit where you reference cloverage

**Comment by drbobbeaty** [comment] 2016-08-10 14:23
@rm-hull Sadly, it was a while and we hadn't heard, so we removed it from the project. We may revisit it later, but not right now.

Nothing against the project... just time.

**Comment by lvh** [comment] 2016-08-15 02:03
@ivajloip @MichaelBlume @codeitagile Do any of you have a remaining reproducer for this problem?

**Comment by atomic-hedgehog** [comment] 2016-08-23 14:52
I was able to work around this by adding the current version of Cheshire as a dependency in my `.lein/profiles.clj`

**Comment by lvh** [comment] 2019-03-07 15:08
Closing this out since there's no reproducer and apparently modern versions of cheshire/jackson resolve the issue.

**Closed by lvh** 2019-03-07 15:08 UTC
