### ISSUE TITLE
Cloverage incorrectly reporting test failures

### ISSUE THREAD

**Issue by wilsonch** [cloverage/cloverage#52] opened 2014-07-08 23:49 UTC
I'm seeing that "lein cloverage" (version 1.0.2) is reporting test failures even though "lein test" is reporting none.

In my code I do catch all exceptions and log them using timbre. Does this impact how cloverage reports errors?

Report as generated by lein cloverage:
Ran 23 tests containing 51 assertions.
5 failures, 0 errors.
Ran tests.
Produced output in /Users/foo/projects/blah/target/coverage .
HTML: file:///Users/foo/projects/blah/target/coverage/index.html

Report as generated by lein test:
Ran 23 tests containing 51 assertions.
0 failures, 0 errors.

**Comment by cksharma11** [comment] 2020-08-04 12:14
@wilsonch  did you find any solution for the same?

**Comment by ghaskins** [comment] 2020-08-04 13:04
I'm seeing something that feels related.  I have been using cloverage for many years and suddenly in the last few days i have tests that pass in lein-test and fail in lein-cloverage.  Whats even odder is that this includes code that used to pass (i.e. there seems to be some kind of retroactive change in behavior).   

Another odd thing that I observe is that even though I have declared cloverage plugin dep as 1.1.2, I seem to be getting 1.1.3.  I also notice that 1.1.3 was released just recently, so I suspect there is a potential correlation.  However, I cant explain how my 1.1.2 code is picking up 1.1.3

```
$ cat project.clj | grep cloverage
            [lein-cloverage "1.1.2"]
$ lein deps :plugin-tree | grep cloverage
Java HotSpot(TM) 64-Bit Server VM warning: Options -Xverify:none and -noverify were deprecated in JDK 13 and will likely be removed in a future release.
Possibly confusing dependencies found:
[lein-bikeshed "0.5.2"] -> [org.clojure/tools.cli "0.3.5"]
 overrides
[lein-cljfmt "0.6.6"] -> [cljfmt "0.6.6"] -> [org.clojure/tools.cli "0.4.2"]

Consider using these exclusions:
[lein-cljfmt "0.6.6" :exclusions [org.clojure/tools.cli]]

 [lein-cloverage "1.1.2"]
```

```
lein cloverage --fail-threshold 85 -e "manetu.attribute-service.main" -e "manetu.attribute-service.db.cassandra" -e "manetu.attribute-service.kafka" -e "manetu.attribute-service.metrics" -e "manetu.attribute-service.account.grpc" -e "manetu.attribute-service.subservice.migrate.core" | perl -pe 's/\e\[?.*?[\@-~]//g'
Retrieving cloverage/cloverage/1.1.3/cloverage-1.1.3.pom from clojars
Retrieving org/clojure/tools.logging/0.5.0/tools.logging-0.5.0.pom from central
Retrieving org/clojure/tools.namespace/0.3.1/tools.namespace-0.3.1.pom from central
Retrieving org/clojure/java.classpath/0.3.0/java.classpath-0.3.0.pom from central
Retrieving org/clojure/data.xml/0.0.8/data.xml-0.0.8.pom from central
Retrieving riddley/riddley/0.2.0/riddley-0.2.0.pom from clojars
Retrieving cloverage/cloverage/1.1.3/cloverage-1.1.3.jar from clojars
```

The only thing that I can think of is somehow the v1.1.2 artifact in clojars was overwritten inadvertently with v1.1.3?

**Comment by lvh** [comment] 2020-08-04 13:57
Given the amount of changes that has happened since this ticket was originally opened it seems extremely unlikely that the issue is actually the same. Please open a new ticket.

That said: the artifact definitely doesn't seem to have been overwritten: Clojars still shows it as having been pushed Oct 2019. That shell log shows cloverage-1.1.3 getting loaded, which tells me cloverage isn't in your deps and the [dependency injection code](https://github.com/cloverage/cloverage/blob/master/lein-cloverage/src/leiningen/cloverage.clj#L27-L28) is adding [`RELEASE`](https://github.com/cloverage/cloverage/blob/master/lein-cloverage/src/leiningen/cloverage.clj#L7-L8) (which is indeed 1.1.3). To revert to 1.1.2, set the `CLOVERAGE_VERSION` env var to 1.1.2. If that works, please try the current 1.2.0-SNAPSHOT to see if it fixes your issue. (You should be able to set that via `CLOVERAGE_VERSION` as well.)

(Closing this now since this ticket just describes a symptom that could come from a whole myriad of things and so it's unlikely to result in any progress, but feel free to open a new one--your description was useful in debugging.)

**Comment by ghaskins** [comment] 2020-08-04 14:02
Ill try the envvar now, ty

**Comment by ghaskins** [comment] 2020-08-04 14:10
Using the envvar trick above, I have confirmed that both 1.1.2 and 1.2.0-SNAPSHOT _work_, and 1.1.3 does _NOT WORK_.  I will open a new ticket with the info.  Ty, and also ty for cloverage in general.  It's an awesome tool.

**Comment by lvh** [comment] 2020-08-04 14:16
If 1.2.0-SNAPSHOT _does_ work you're just getting bit by the same bug as #298 I think :)

**Comment by lvh** [comment] 2020-08-04 14:28
I have just cut 1.2.0 since it appears to fix multiple people's issue.

**Closed by lvh** 2020-08-04 14:28 UTC
